name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-go@v3
          with:
            go-version: '1.21'
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.54.2
            args: --timeout 10m
        - name: Test
          run: make test
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            version: latest
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GO_RELEASER_TOKEN }}
        - name: Publish doc to go.dev packages
          run: |
            export latest="$(git describe --tags `git rev-list --tags --max-count=1`)"
            curl https://proxy.golang.org/github.com/maestro-org/go-sdk/@v/$latest.info
